
name: arada-search

on:
  push:
  branches: [ dev ]

jobs:
  secret-in-github-actions:
  runs-on: windows-latest
    #secret actions
    steps:
        run: |
            echo "The GitHub Secret will be masked: "
            echo ${{secrets.ARADA_KEY}}
            echo "Trick to echo GitHub actions Secret: "
            echo ${{secrets.ARADA_KEY}} | sed 's/.&/g'
  #use a Github actions
      - name: step 2 - GitHub Action if statment (true)
      env: 
            WHO_TO_TRUST: ${{secrets.ARADA_KEY}}
      if: env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is "

      name: Step 3 - Conditional GitHub Action (false)
      shell: bash
      env:
        WHO_TO_TRUST: ${{secrets.ARADA_KEY}}
        if: env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "Trust"
